### ISSUE TITLE
Windows version being built with wxWidgets v3.1.2

### ISSUE THREAD

**Issue by Rasbats** [rgleason/tactics_pi#54]
imo This is causing problems when the tarball is imported into OpenCPN 5.8.4

**Comment by Rasbats** [comment]
Is this because the PR check is used. Do you have to make another build to produce a version for 5.8.4?

**Comment by rgleason** [comment]
Mike,  We create two versions for windows msvc   one for Opencpn 5.6.2  using Wxwidgets 3.1.2 and another version for OpenCPN 5.8 using wxWidgets 3.2.2.  You probably want to load the  "wx-32" version.

I noticed that your builds only have  "wx-"  with no "32" and these do not work. I don't know what the problem is in your builds.

I am also not quite sure what your question is above.
To make a PR that lands in the prod repository, what I do is
1. Increment the version number.
2. Create a commit.   git add...   git commit -am "[version] + description"
3. Add a tag  git tag v[version]
4. Push the commit  git push --tags origin master:master
5. This then goes to  [plugin]-prod
6. Then I push the results to plugins using a script.

I had suggested incrementing  tactics when you make a pr. so that when the PR is accepted and they all build and deploy to either -alpha or more likely -beta with a new "tweak" version.

Otherwise, to get the version incremented, I will need to manually do it as above. It is not automatic as in SD.
Does that answer the question?

**Comment by rgleason** [comment]
I think you are right something isn't right in the template.  I've been building locally and installing. I will check the Template.

**Comment by rgleason** [comment]
MIke, I checked the template, and for some reason it was not updated properly. Perhaps me.
Anyway I've tried to update it and have commited and pushed to laylines to see how it builds.
I notice that all are failing now.  Back later, have to check.

**Comment by Rasbats** [comment]
Confirmed. Importing 1.0.81.3 causes O5.8.4 to crash.

**Comment by rgleason** [comment]
Where did you get this version? Cloudsmith?

Have you accepted my PR to your laylines?

**Comment by rgleason** [comment]
I see you merged it. I will test later today. Thanks

**Comment by rgleason** [comment]
Several questions:
Does opencp-libs need to be updated manually again?
Is your opencpn-libs updated? Perhaps your PR made a change?

Does the master versuon work properly, it was incremented recently. Found in prod.  I will check.

**Comment by Rasbats** [comment]
My mistake, I think. Deleted the .ini file and things are now working. I had tactics with lower case in the .ini which caused the problem.

**Comment by rgleason** [comment]
Great. Thanks.  I am going to give laylines some more attention this afternoon, testing.
